### PR TITLE
add edit profile page

### PR DESCRIPTION
**Pull request by Ogollah**
#### What does this PR do?
Create edit profile page

#### Description of Task to be completed
A user should be able to edit their profile

#### How should I test it manually?
Clone this repository
Open your terminal
cd Ride-my-way
git checkout ft-edit-profile158518129
Open edit-profile.html using your favorite browser

#### What PT stories?
[ft-158518129](https://www.pivotaltracker.com/story/show/158518129)
#### screenshot

eddy

### CODE REVIEW

**Comment by meshack-mbuvi** [comment]
looks good to me

**Comment by artorious** [comment]
Looks good brother.
Question,
You have a file upload on the form,
Is it an alternative to filling the form?

**Comment by JoshuaOndieki** [comment]
I don't think it's wise merging code into another feature.
I.e. I assume Feature **offer** and Feature **Edit-profile** are unrelated.
And so merging them doesn't make sense, at least to me.

**Comment by Ogollah** [comment]
@artorious Thanks for that observation

**Comment by Ogollah** [comment]
@JoshuaOndieki Taken that into consideration, it a learning process. You accept correction so that you do not repeat them again.

**Review by LWanjiru — CHANGES_REQUESTED** [review]
Please look into the comments I made on your previous PR here ==> https://github.com/Ogollah/Ride-my-way/pull/12#pullrequestreview-130925190

**Comment by LWanjiru** [comment]
Please resolve the conflicts. Also, please have a look at this resource on the best practices when designing web pages ==> https://www.crowdspring.com/blog/small-business-web-design-best-practices-and-tips/

**Pull request merged**
