### PR TITLE
modify ride page add bacgroun-color

### PR DESCRIPTION
**Pull request by Ogollah**
#### What does this PR do?
Create buttons in the home page
Modify ride page 

#### Description of Task to be completed
A user should be able to see the list of available rides
A user should be able to navigate to the ride details and request for a ride
A user should be able to see the details of a ride

#### How should I test it manually?
Clone this repository
Open your terminal
cd Ride-my-way
git checkout ft-ride-page-#158454339
Open ride.html using your favorite browser

#### What PT stories?
[ft-#158454339] (https://www.pivotaltracker.com/story/show/158454339)
#### Screenshot
hor

### CODE REVIEW

**Review by JoshuaOndieki — CHANGES_REQUESTED** [review]
I've checked in all screen sizes and your *Request Ride* Button appears behind the footer at all times.
What effect does this have? The button becomes partially invisible and maybe unclickable

screencapture-cdn-rawgit-ogollah-ride-my-way-37252d314f2e79345de44b6079e2be54a7a1033e-ui-templates-ride-html-2018-06-23-12_05_14

**Comment by Ogollah** [comment]
@JoshuaOndieki Have a look at it now

**Comment by meshack-mbuvi** [comment]
The ui is nice to me.
Just curious thought. Suppose you had 1000 ride offers in you app, how long do you think users will have to scroll looking for a specific ride offer?
Am thinking you should just pick like 3-4 items which are most important to users and just show that.Then you provide a way for users to view more details about the given ride offer. How does that look?

**Comment by Ogollah** [comment]
@meshack-mbuvi I have a page for that, this is page show details of a single ride offer.

**Review by JoshuaOndieki — CHANGES_REQUESTED** [review]
Improvements have been made.
Though, find a way to get rid of the horizontal scroll bar on smaller screens.

**Review by JoshuaOndieki — APPROVED** [review]
:1st_place_medal:

**Pull request merged**
