### PR TITLE
Ft edit offer 158575083

### PR DESCRIPTION
**Pull request by Ogollah**
#### What does this PR do?
Design a edit-offer page  

#### Description of Task to be completed
A user should be able to navigate to edit offer page
A user should be able to edit their ride offer.

#### How should I test it manually?
Clone this repository
Open your terminal
cd Ride-my-way
git checkout ft-edit offer-158575083
Open edit-offer.html using your favorite browser

#### What PT stories?
[Ft-158575083](https://www.pivotaltracker.com/story/show/158575083)
#### Screenshot
mob-edit-prof

### CODE REVIEW

**Comment by meshack-mbuvi** [comment]
This is awesome

**Comment by JoshuaOndieki** [comment]
Considering the changes made, your commits:

1. *e6c7fa5* **Add edit-offer page**
2. *d54aeb4* **Add edit-offer page**
3. *7faf897* **Update edit-offer page**

Are way too ambiguous.

**Comment by JoshuaOndieki** [comment]
Here's how the footer looks on my screen (15.1in)

screencapture-cdn-rawgit-ogollah-ride-my-way-7faf897b6975b69ad733af9267a3c0e6dbf27542-ui-templates-edit-offer-html-2018-06-23-14_00_25

**Comment by Ogollah** [comment]
@JoshuaOndieki how is it now?

**Review by JoshuaOndieki — APPROVED** [review]
Looks great on mobile now. Kudos :+1: :+1: :+1:

**Comment by artorious** [comment]
Looks Great, we have come a long ways. 💪

**Pull request merged**
