### PR TITLE
Ft profile 158422941

### PR DESCRIPTION
**Pull request by Ogollah**
#### What does this PR do?
Create a profile page
Create a create ride form

#### Description of Task to be completed
A user should be able to see their activities
A user should be able to add a new ride
A user should be able to see to see their details
A user should be able to delete expired rides

#### How should I test it manually?
Clone this repository
Open your terminal
cd Ride-my-way
git checkout ft-profile-158422941
Open ride.html using your favorite browser

#### What PT stories?
[ft-158422941](https://www.pivotaltracker.com/story/show/158422941)
#### Screenshot
profile_rev
prof

### CODE REVIEW

**Review by JoshuaOndieki — APPROVED** [review]
:+1: Great work :sparkles: on these changes.

P.S. As much as I approve these changes, I would like to point out that your single commit *446c41f* : **Add delete button** does not really describe all these changes made.

**Comment by JoshuaOndieki** [comment]
You probably want to look into the mobile version of your UI.
Suggested Layout: I'd suggest having the **My Rides** table just below the profile details section for the mobile version.

screencapture-cdn-rawgit-ogollah-ride-my-way-446c41f50dc52a5360c9ef54523024c97829711a-ui-templates-profile-html-2018-06-23-16_58_30

**Comment by Ogollah** [comment]
Sure I will @JoshuaOndieki

**Comment by Ogollah** [comment]
@JoshuaOndieki look at it now.

**Review by JoshuaOndieki — APPROVED** [review]
Hoped for the *my rides* profile section to appear below your current left section which is containing the user's details.
However, this calls for a change in design which I would suggest adding it to your Pivotal Tracker but give it less priority since you have other tasks that need to be delivered ASAP.
I may raise an *Issue* about this to remind you about the suggestion.

**Pull request merged**
