### PR TITLE
[ft-#158439537] modify welcome page

### PR DESCRIPTION
**Pull request by Ogollah**
#### What does this PR do?
Modify welcome page to match the requirements

#### Description of Task to be completed
A user should be able to see a welcome message

#### How should I test it manually?
Clone this repository
Open your terminal
cd Ride-my-way
git checkout ft-welcome-page-158439537

Open welcome.html using a browser of your choice

#### What PT stories?
[ft-#158439537] (https://www.pivotaltracker.com/story/show/158439537)

#### Screenshot
new

### CODE REVIEW

**Comment by meshack-mbuvi** [comment]
I have seen you have several PRs all about welcome page, I ma thinking you should be having one to which you should be committing your changes. This way, you will be able to track whatever you do. Think of atomicity in your PRs.

**Comment by LWanjiru** [comment]
I observe that the User Interface is not so user-friendly. The colours are highly contrasting and competing with each other, some of the text is hard to read. Also, observe good grammar, it is part of what makes a webpage user-friendly.

**Comment by Ogollah** [comment]
@LWanjiru @meshack-mbuvi How is it now?

**Comment by artorious** [comment]
Big improvement. Keep tweeking it. Solid fonts work best. White on gray(ish) still problematic for some people.

**Comment by Ogollah** [comment]
@artorious how about now?

**Comment by meshack-mbuvi** [comment]
It looks better than before. keep it up

**Comment by LWanjiru** [comment]
Major improvement. However, keep working towards a more friendly appearance.  Can be merged.

**Pull request merged**
